services:
  langmanus-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    image: langmanus-web
    ports:
      - "9875:3000"
    env_file:
      - .env
